apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ag-ui-app
spec:
  template:
    spec:
      containers:
      - name: my-ag-ui-app
        livenessProbe:
          httpGet:
            path: /health
        readinessProbe:
          httpGet:
            path: /health